import BarcodeScanner from "@/src/components/BarcodeScanner";
import Head from "next/head";
import React from "react";

export default function Home(props: any) {
  const [isActive, setIsActive] = React.useState(false);
  const [initialized, setInitialized] = React.useState(false);

  const toggleScanning = () => {
    setIsActive(!isActive);
  }

  const onScanned = (results: TextResult[]) => {
    if (results.length > 0) {
      let text = "";
      for (let index = 0; index < results.length; index++) {
        const result = results[index];
        text = text + result.barcodeFormatString + ": " + result.barcodeText + "\n";
      }
      alert(text);
      setIsActive(false);
    }
  }
  return (
    <>
      <Head>
        <title>Next.js Barcode Reader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={""}>
          <h2>Next.js Barcode Scanner</h2>
          <button onClick={toggleScanning}>{isActive ? "Stop Scanning" : "Start Scanning"}</button>

          <div className={""}>



            {initialized ? (
              <button onClick={toggleScanning}>{isActive ? "Stop Scanning" : "Start Scanning"}</button>
            ) : (
              <div>Initializing...</div>
            )}
            <BarcodeScanner

              license={props.license}
              onInitialized={() => setInitialized(true)}
              isActive={isActive}
              onScanned={(results) => onScanned(results)}
            ></BarcodeScanner>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  let license: string | undefined = "DLS2eyJoYW5kc2hha2VDb2RlIjoiMTAzNDAwODQzLVRYbFFjbTlxIiwibWFpblNlcnZlclVSTCI6Imh0dHBzOi8vbWRscy5keW5hbXNvZnRvbmxpbmUuY29tIiwib3JnYW5pemF0aW9uSUQiOiIxMDM0MDA4NDMiLCJzdGFuZGJ5U2VydmVyVVJMIjoiaHR0cHM6Ly9zZGxzLmR5bmFtc29mdG9ubGluZS5jb20iLCJjaGVja0NvZGUiOi00NDc0NjAxNX0=";
  return { props: { license: license } };
}